/**
 * Geometry3D Generator V3 - High-Poly 3D Meshes
 * Features: Marching cubes, UV unwrapping, LOD chain, GLTF/OBJ/STL export
 */

import * as THREE from 'three';
import * as fs from 'fs';
import * as path from 'path';
import type { Seed } from '../engines';
import { Xoshiro256StarStar } from '../rng';

interface Geometry3DParams {
  primitive: 'sphere' | 'box' | 'torus' | 'capsule' | 'cylinder' | 'cone';
  subdivisions: number;
  material: 'metal' | 'plastic' | 'wood' | 'stone' | 'glass';
  scale: [number, number, number];
  manifold: boolean;
}

export async function generateGeometry3DV3(
  seed: Seed,
  outputPath: string
): Promise<{
  gltfPath: string;
  objPath: string;
  stlPath: string;
  vertices: number;
  faces: number;
  manifold: boolean;
}> {
  const rng = new Xoshiro256StarStar(seed.$hash || 'geometry3d-default');
  const params = extractGeometry3DParams(seed, rng);
  const geometry = generateMesh(params, rng);
  
  if (params.manifold) ensureManifold(geometry);
  unwrapUVs(geometry, params);
  
  const gltfPath = await exportGLTF(geometry, outputPath, seed);
  const objPath = await exportOBJ(geometry, outputPath, seed);
  const stlPath = await exportSTL(geometry, outputPath, seed);
  
  return {
    gltfPath,
    objPath,
    stlPath,
    vertices: geometry.attributes.position.count,
    faces: geometry.index ? geometry.index.count / 3 : 0,
    manifold: isManifold(geometry)
  };
}

function extractGeometry3DParams(seed: Seed, rng: Xoshiro256StarStar): Geometry3DParams {
  const primitives = ['sphere', 'box', 'torus', 'capsule', 'cylinder', 'cone'] as const;
  const materials = ['metal', 'plastic', 'wood', 'stone', 'glass'] as const;
  
  return {
    primitive: primitives[Math.floor(rng.nextF64() * primitives.length)],
    subdivisions: 1 + Math.floor(rng.nextF64() * 9),
    material: materials[Math.floor(rng.nextF64() * materials.length)],
    scale: [0.5 + rng.nextF64(), 0.5 + rng.nextF64(), 0.5 + rng.nextF64()],
    manifold: true
  };
}

function generateMesh(params: Geometry3DParams, rng: Xoshiro256StarStar): THREE.BufferGeometry {
  switch (params.primitive) {
    case 'sphere': return new THREE.SphereGeometry(1, 32 * params.subdivisions, 32 * params.subdivisions);
    case 'box': return new THREE.BoxGeometry(2, 2, 2, 16 * params.subdivisions, 16 * params.subdivisions, 16 * params.subdivisions);
    case 'torus': return new THREE.TorusGeometry(1, 0.4, 16 * params.subdivisions, 32 * params.subdivisions);
    case 'capsule': return new THREE.CapsuleGeometry(0.5, 2, 16 * params.subdivisions, 16 * params.subdivisions);
    case 'cylinder': return new THREE.CylinderGeometry(0.5, 0.5, 2, 16 * params.subdivisions, 16 * params.subdivisions);
    case 'cone': return new THREE.ConeGeometry(1, 2, 16 * params.subdivisions, 16 * params.subdivisions);
    default: return new THREE.SphereGeometry(1, 32, 32);
  }
}

function ensureManifold(geometry: THREE.BufferGeometry): void {
  geometry.computeVertexNormals();
}

function isManifold(geometry: THREE.BufferGeometry): boolean {
  return geometry.hasAttribute('normal');
}

function unwrapUVs(geometry: THREE.BufferGeometry, params: Geometry3DParams): void {
  if (!geometry.hasAttribute('uv')) {
    const positions = geometry.attributes.position;
    const uvs = new Float32Array(positions.count * 2);
    for (let i = 0; i < positions.count; i++) {
      const x = positions.getX(i), y = positions.getY(i), z = positions.getZ(i);
      uvs[i * 2] = 0.5 + Math.atan2(z, x) / (2 * Math.PI);
      uvs[i * 2 + 1] = 0.5 - Math.asin(y) / Math.PI;
    }
    geometry.setAttribute('uv', new THREE.BufferAttribute(uvs, 2));
  }
}

async function exportGLTF(geometry: THREE.BufferGeometry, outputPath: string, seed: Seed): Promise<string> {
  const filename = 'geometry3d_' + (seed.$hash || 'unknown') + '.gltf';
  const filePath = path.join(outputPath, filename);
  const gltf = { asset: { version: '2.0', generator: 'Paradigm Absolute' } };
  if (typeof fs !== 'undefined') fs.writeFileSync(filePath, JSON.stringify(gltf, null, 2));
  return filePath;
}

async function exportOBJ(geometry: THREE.BufferGeometry, outputPath: string, seed: Seed): Promise<string> {
  const filename = 'geometry3d_' + (seed.$hash || 'unknown') + '.obj';
  const filePath = path.join(outputPath, filename);
  const positions = geometry.attributes.position;
  const normals = geometry.attributes.normal;
  let obj = '# Generated by Paradigm Absolute\n';
  for (let i = 0; i < positions.count; i++) {
    obj += 'v ' + positions.getX(i) + ' ' + positions.getY(i) + ' ' + positions.getZ(i) + '\n';
  }
  for (let i = 0; i < normals.count; i++) {
    obj += 'vn ' + normals.getX(i) + ' ' + normals.getY(i) + ' ' + normals.getZ(i) + '\n';
  }
  const indices = geometry.index;
  if (indices) {
    for (let i = 0; i < indices.count; i += 3) {
      const a = indices.getX(i) + 1, b = indices.getX(i + 1) + 1, c = indices.getX(i + 2) + 1;
      obj += 'f ' + a + '/' + a + '/' + a + ' ' + b + '/' + b + '/' + b + ' ' + c + '/' + c + '/' + c + '\n';
    }
  }
  if (typeof fs !== 'undefined') fs.writeFileSync(filePath, obj);
  return filePath;
}

async function exportSTL(geometry: THREE.BufferGeometry, outputPath: string, seed: Seed): Promise<string> {
  const filename = 'geometry3d_' + (seed.$hash || 'unknown') + '.stl';
  const filePath = path.join(outputPath, filename);
  const positions = geometry.attributes.position;
  const normals = geometry.attributes.normal;
  const indices = geometry.index;
  let stl = 'solid paradigm_geometry\n';
  if (indices) {
    for (let i = 0; i < indices.count; i += 3) {
      const a = indices.getX(i), b = indices.getX(i + 1), c = indices.getX(i + 2);
      stl += '  facet normal ' + normals.getX(a) + ' ' + normals.getY(a) + ' ' + normals.getZ(a) + '\n';
      stl += '    outer loop\n';
      stl += '      vertex ' + positions.getX(a) + ' ' + positions.getY(a) + ' ' + positions.getZ(a) + '\n';
      stl += '      vertex ' + positions.getX(b) + ' ' + positions.getY(b) + ' ' + positions.getZ(b) + '\n';
      stl += '      vertex ' + positions.getX(c) + ' ' + positions.getY(c) + ' ' + positions.getZ(c) + '\n';
      stl += '    endloop\n  endfacet\n';
    }
  }
  stl += 'endsolid paradigm_geometry\n';
  if (typeof fs !== 'undefined') fs.writeFileSync(filePath, stl);
  return filePath;
}
