/**
 * Meta-Domain Generators — Beyond Omega
 * domain_generator, engine_generator, gene_generator, functor_generator
 * Recursive self-improvement: platforms that generate themselves
 */

import * as fs from 'fs';
import * as path from 'path';
import type { Seed } from '../engines';
import { Xoshiro256StarStar, rngFromHash } from '../rng';

// --- Domain Generator ---
interface DomainGenParams {
  count: number;
  complexity: number;
  quality: 'low' | 'medium' | 'high' | 'photorealistic';
}

export async function generateDomainGenerator(seed: Seed, outputPath: string): Promise<{ filePath: string; domainsGenerated: number }> {
  const rng = rngFromHash(seed.$hash || '');
  const params = extractDomainGenParams(seed, rng);

  // Generate new domain definitions
  const domains = Array.from({ length: params.count }, (_, i) => ({
    id: `domain_${i}`,
    name: generateDomainName(rng),
    geneTypes: generateGeneTypesForDomain(rng, params.complexity),
    engineType: ['generator', 'simulator', 'renderer', 'composer'][rng.nextInt(0, 3)],
    quality: params.quality
  }));

  // Generate functor bridges between new domains
  const functors = generateFunctorBridges(domains, rng);

  const config = {
    metaDomain: 'domain_generator',
    generated: new Date().toISOString(),
    seedHash: seed.$hash || '',
    count: domains.length,
    domains,
    functors,
    recursiveDepth: 0, // Can generate domains that generate domains...
    quality: params.quality
  };

  const dir = path.dirname(outputPath);
  if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });

  const jsonPath = outputPath.replace(/\.json$/, '_domain-gen.json');
  fs.writeFileSync(jsonPath, JSON.stringify(config, null, 2));

  return {
    filePath: jsonPath,
    domainsGenerated: domains.length
  };
}

function generateDomainName(rng: Xoshiro256StarStar): string {
  const prefixes = ['neuro', 'quantum', 'bio', 'astro', 'nano', 'cyber', 'chrono', 'psycho'];
  const suffixes = ['field', 'dynamics', 'network', 'system', 'space', 'topology', 'wave'];
  return `${prefixes[rng.nextInt(0, prefixes.length - 1)]}_${suffixes[rng.nextInt(0, suffixes.length - 1)]}`;
}

function generateGeneTypesForDomain(rng: Xoshiro256StarStar, complexity: number): string[] {
  const allTypes = [
    'scalar', 'categorical', 'vector', 'expression', 'struct',
    'array', 'graph', 'topology', 'temporal', 'regulatory',
    'field', 'symbolic', 'quantum', 'gematria', 'resonance',
    'dimensional', 'sovereignty'
  ];
  const count = Math.floor(3 + complexity * (allTypes.length - 3));
  const selected: string[] = [];
  for (let i = 0; i < count; i++) {
    selected.push(allTypes[rng.nextInt(0, allTypes.length - 1)]);
  }
  return [...new Set(selected)]; // unique
}

function generateFunctorBridges(domains: any[], rng: Xoshiro256StarStar): any[] {
  const bridges: any[] = [];
  for (let i = 0; i < domains.length; i++) {
    for (let j = i + 1; j < domains.length; j++) {
      if (rng.nextF64() < 0.3) { // 30% chance of bridge
        bridges.push({
          from: domains[i].name,
          to: domains[j].name,
          type: ['morph', 'translate', 'evolve'][rng.nextInt(0, 2)],
          coherence: rng.nextF64()
        });
      }
    }
  }
  return bridges;
}

function extractDomainGenParams(seed: Seed, rng: Xoshiro256StarStar): DomainGenParams {
  return {
    count: Math.floor((seed.genes?.count?.value || 0.5) * 20) + 2,
    complexity: seed.genes?.complexity?.value || rng.nextF64(),
    quality: ['low', 'medium', 'high', 'photorealistic'].includes(seed.genes?.quality?.value) 
      ? seed.genes.quality.value : 'medium'
  };
}

// --- Engine Generator ---
export async function generateEngineGenerator(seed: Seed, outputPath: string): Promise<{ filePath: string; enginesGenerated: number }> {
  const rng = rngFromHash(seed.$hash || '');
  
  const engines = Array.from({ length: 5 }, (_, i) => ({
    id: `engine_${i}`,
    name: `GeneratedEngine_${i}`,
    domain: generateDomainName(rng),
    code: generateEngineCode(rng),
    performance: {
      fps: rng.nextF64() * 60 + 30,
      memory: rng.nextF64() * 1000 + 100,
      accuracy: rng.nextF64()
    }
  }));

  const config = {
    metaDomain: 'engine_generator',
    engines,
    canSelfModify: true,
    quality: 'photorealistic'
  };

  const jsonPath = outputPath.replace(/\.json$/, '_engine-gen.json');
  fs.writeFileSync(jsonPath, JSON.stringify(config, null, 2));

  return {
    filePath: jsonPath,
    enginesGenerated: engines.length
  };
}

function generateEngineCode(rng: Xoshiro256StarStar): string {
  return `/**
 * Auto-Generated Engine (Beyond Omega)
 * This engine was generated by another engine
 */

export class GeneratedEngine {
  constructor(private config: any) {}
  
  async process(seedHash: string): Promise<any> {
    const rng = rngFromHash(seedHash);
    return {
      output: \`Generated output from \${this.config.name}\`,
      confidence: ${rng.nextF64()}
    };
  }
}`;
}

// --- Gene Generator ---
export async function generateGeneGenerator(seed: Seed, outputPath: string): Promise<{ filePath: string; geneTypesGenerated: number }> {
  const rng = rngFromHash(seed.$hash || '');
  
  const newGeneTypes = Array.from({ length: 5 }, (_, i) => ({
    id: `gene_${Date.now()}_${i}`,
    name: `custom_gene_${i}`,
    baseType: ['scalar', 'vector', 'struct', 'graph'][rng.nextInt(0, 3)],
    operators: {
      validate: generateValidationCode(rng),
      mutate: generateMutationCode(rng),
      crossover: generateCrossoverCode(rng),
      distance: generateDistanceCode(rng)
    },
    quality: 'photorealistic'
  }));

  const config = {
    metaDomain: 'gene_generator',
    newGeneTypes,
    canEvolve: true,
    quality: 'photorealistic'
  };

  const jsonPath = outputPath.replace(/\.json$/, '_gene-gen.json');
  fs.writeFileSync(jsonPath, JSON.stringify(config, null, 2));

  return {
    filePath: jsonPath,
    geneTypesGenerated: newGeneTypes.length
  };
}

function generateValidationCode(rng: Xoshiro256StarStar): string {
  return `return typeof value === '${['number', 'string', 'object'][rng.nextInt(0, 2)]}';`;
}

function generateMutationCode(rng: Xoshiro256StarStar): string {
  return `value = value * (1 + (rng.nextF64() - 0.5) * 0.1); return value;`;
}

function generateCrossoverCode(rng: Xoshiro256StarStar): string {
  return `return rng.nextF64() < 0.5 ? parentA : parentB;`;
}

function generateDistanceCode(rng: Xoshiro256StarStar): string {
  return `return Math.abs(a - b) / (a + b || 1);`;
}
