/**
 * CodeSmith — Stage 2 Sub-Agent
 *
 * Transforms an IntentEnvelope into GSPL source code.
 * Deterministic template-based generation for now;
 * can be LLM-enhanced for more creative code generation.
 */

import type { SubAgent, AgentMessage, AgentResult, AgentContext, IntentEnvelope, CodeGenOutput } from './SubAgent';
import crypto from 'crypto';

export class CodeSmith implements SubAgent {
  name = 'CodeSmith';
  stage = 2;
  isLLMBacked = false;
  hasToolAccess = false;
  toolNames: string[] = [];

  async execute(input: AgentMessage, ctx: AgentContext): Promise<AgentResult> {
    const intent = input.payload as IntentEnvelope;

    if (!intent || !intent.domain) {
      return { success: false, type: 'code:error', payload: { error: 'Invalid intent: missing domain' } };
    }

    const gsplCode = this.generateCode(intent);
    const params = intent.genes;

    return {
      success: true,
      type: 'code:generated',
      payload: { gsplCode, params } as CodeGenOutput,
      metadata: { domain: intent.domain, geneCount: Object.keys(intent.genes).length },
    };
  }

  private generateCode(intent: IntentEnvelope): string {
    const paramEntries = Object.entries(intent.genes)
      .map(([k, v]) => `  "${k}": ${JSON.stringify(v)}`)
      .join(',\n');

    const hash = crypto.createHash('sha256')
      .update(`${intent.domain}:${intent.description}:${JSON.stringify(intent.genes)}`)
      .digest('hex')
      .slice(0, 12);
    const name = `${intent.domain}_${hash}`;

    // Improved multi-step constrained GSPL (post-supremacy: includes strata for orchestration, multi ops for plans, beyond simple heuristic)
    // Uses strata decl + grow + evolve/mutate/compose with constraints. Agent can surface for inspect/edit in GSPLEditor.
    const strataLine = intent.style && intent.style.includes('mind') ? '  strata: Form + Mind + Story ;' : '  strata: Form + Mind + World ;';

    return [
      `// GSPL multi-step plan — Generated by CodeSmith (strengthened for lived seamlessness)`,
      `// Intent: ${intent.description}`,
      `// Domain: ${intent.domain}  Style: ${intent.style}`,
      `// Note: inspect/edit this in GSPLEditor, or adjust strata in GeneEditor for live sync`,
      ``,
      `seed ${name} in ${intent.domain} {`,
      strataLine,
      paramEntries,
      `}`,
      ``,
      `// Step 1: base growth with strata constraints (orchestrates rich gen via supremacy layer)`,
      `let base = grow(${name})`,
      ``,
      `// Step 2: evolve/mutate under strata (multi-step plan)`,
      `let evolved = evolve(base, generations: 2, strata: ["Mind"])`,
      ``,
      `// Step 3: cross-domain compose (GSPL as control layer)`,
      `let final = compose(evolved, to: "music")`,
      ``,
      `// final artifact ready for rich preview + .gseed`,
    ].join('\n');
  }

  /**
   * Refine existing GSPL code based on validation feedback.
   * Called during the refine cycle when validation fails.
   */
  refine(_gsplCode: string, issues: string[], intent: IntentEnvelope): string {
    const header = `// Refined GSPL — addressing: ${issues.join('; ')}\n`;
    const body = this.generateCode(intent);
    return header + body;
  }
}
