/**
 * CodeSmith — Stage 2 Sub-Agent
 *
 * Transforms an IntentEnvelope into GSPL source code.
 * Deterministic template-based generation for now;
 * can be LLM-enhanced for more creative code generation.
 */

import type { SubAgent, AgentMessage, AgentResult, AgentContext, IntentEnvelope, CodeGenOutput } from './SubAgent';
import crypto from 'crypto';

export class CodeSmith implements SubAgent {
  name = 'CodeSmith';
  stage = 2;
  isLLMBacked = false;
  hasToolAccess = false;
  toolNames: string[] = [];

  async execute(input: AgentMessage, ctx: AgentContext): Promise<AgentResult> {
    const intent = input.payload as IntentEnvelope;

    if (!intent || !intent.domain) {
      return { success: false, type: 'code:error', payload: { error: 'Invalid intent: missing domain' } };
    }

    const gsplCode = this.generateCode(intent);
    const params = intent.genes;

    return {
      success: true,
      type: 'code:generated',
      payload: { gsplCode, params } as CodeGenOutput,
      metadata: { domain: intent.domain, geneCount: Object.keys(intent.genes).length },
    };
  }

  private generateCode(intent: IntentEnvelope): string {
    const paramEntries = Object.entries(intent.genes)
      .map(([k, v]) => `  "${k}": ${JSON.stringify(v)}`)
      .join(',\n');

    const hash = crypto.createHash('sha256')
      .update(`${intent.domain}:${intent.description}:${JSON.stringify(intent.genes)}`)
      .digest('hex')
      .slice(0, 12);

    return [
      `// GSPL — Generated by CodeSmith`,
      `// Intent: ${intent.description}`,
      `// Domain: ${intent.domain}  Style: ${intent.style}`,
      ``,
      `seed ${intent.domain}_${hash} in ${intent.domain} {`,
      paramEntries,
      `}`,
      ``,
      `// Operations`,
      `// grow(${intent.domain}_${hash})`,
      ``,
    ].join('\n');
  }

  /**
   * Refine existing GSPL code based on validation feedback.
   * Called during the refine cycle when validation fails.
   */
  refine(gsplCode: string, issues: string[], intent: IntentEnvelope): string {
    const header = `// Refined GSPL — addressing: ${issues.join('; ')}\n`;
    const body = this.generateCode(intent);
    return header + body;
  }
}
