/**
 * GSPL GPU Compiler — @gpu Directive Implementation
 * Compiles GSPL functions annotated with @gpu to WGSL (WebGPU Shading Language)
 * Phase I.1: Full GSPL Completeness
 */

import type { ASTNode, ASTNodeType } from './gspl-parser';

interface GPUFunction {
  name: string;
  params: { name: string; type: string }[];
  returnType: string;
  body: ASTNode[];
  isGPU: boolean;
}

interface WGSLCompileResult {
  wgslCode: string;
  entryPoint: string;
  workgroupSize: [number, number, number];
  errors: string[];
}

/**
 * Compile GSPL AST to WGSL
 */
export function compileToWGSL(ast: ASTNode[]): WGSLCompileResult {
  const errors: string[] = [];
  let wgslCode = '';
  
  // WGSL header
  wgslCode += '// Generated by Paradigm GSPL → WGSL compiler\n';
  wgslCode += '// DO NOT EDIT — Generated code\n\n';
  
  // Add common WGSL utilities
  wgslCode += generateUtilities();
  
  // Process each top-level function
  for (const node of ast) {
    if (node.type === ASTNodeType.FUNCTION_DEF) {
      const func = parseGPUFunction(node);
      if (func.isGPU) {
        wgslCode += compileFunctionToWGSL(func);
      }
    }
  }
  
  return {
    wgslCode,
    entryPoint: 'main',
    workgroupSize: [16, 16, 1],
    errors
  };
}

/**
 * Parse GPU function from AST
 */
function parseGPUFunction(node: ASTNode): GPUFunction {
  const name = node.name || 'unknown';
  const params = (node.params || []).map((p: any) => ({
    name: p.name,
    type: mapGSLTypeToWGSL(p.type || 'scalar')
  }));
  const returnType = mapGSLTypeToWGSL(node.returnType || 'void');
  const isGPU = node.directives?.includes('@gpu') || false;
  
  return {
    name,
    params,
    returnType,
    body: node.body || [],
    isGPU
  };
}

/**
 * Compile a single function to WGSL
 */
function compileFunctionToWGSL(func: GPUFunction): string {
  let code = '';
  
  // Function signature
  code += `fn ${func.name}(`;
  code += func.params.map(p => `${p.name}: ${p.type}`).join(', ');
  code += `): ${func.returnType} {\n`;
  
  // Convert body statements
  for (const stmt of func.body) {
    code += compileStatement(stmt, 2);
  }
  
  code += '}\n\n';
  return code;
}

/**
 * Compile a single statement
 */
function compileStatement(node: ASTNode, indent: number): string {
  const pad = ' '.repeat(indent);
  
  switch (node.type) {
    case ASTNodeType.LET_STATEMENT: {
      const varName = node.name;
      const varType = mapGSLTypeToWGSL(node.valueType || 'f32');
      const value = compileExpression(node.value);
      return `${pad}let ${varName}: ${varType} = ${value};\n`;
    }
    
    case ASTNodeType.ASSIGNMENT: {
      const left = compileExpression(node.left);
      const right = compileExpression(node.right);
      return `${pad}${left} = ${right};\n`;
    }
    
    case ASTNodeType.RETURN: {
      const value = compileExpression(node.value);
      return `${pad}return ${value};\n`;
    }
    
    case ASTNodeType.IF: {
      let code = `${pad}if (${compileExpression(node.condition)}) {\n`;
      for (const stmt of node.thenBody || []) {
        code += compileStatement(stmt, indent + 2);
      }
      if (node.elseBody && node.elseBody.length > 0) {
        code += `${pad}} else {\n`;
        for (const stmt of node.elseBody) {
          code += compileStatement(stmt, indent + 2);
        }
      }
      code += `${pad}}\n`;
      return code;
    }
    
    case ASTNodeType.FOR: {
      const init = compileStatement(node.init, 0).trim();
      const cond = compileExpression(node.condition);
      const update = compileExpression(node.update);
      let code = `${pad}for (${init} ${cond}; ${update}) {\n`;
      for (const stmt of node.body || []) {
        code += compileStatement(stmt, indent + 2);
      }
      code += `${pad}}\n`;
      return code;
    }
    
    default:
      return `${pad}// Unsupported statement: ${node.type}\n`;
  }
}

/**
 * Compile an expression
 */
function compileExpression(node: ASTNode): string {
  switch (node.type) {
    case ASTNodeType.INT_LITERAL:
      return node.value.toString();
    
    case ASTNodeType.FLOAT_LITERAL:
      return `${node.value}f`; // WGSL float literal
    
    case ASTNodeType.STRING_LITERAL:
      return `"${node.value}"`;
    
    case ASTNodeType.BOOLEAN_LITERAL:
      return node.value ? 'true' : 'false';
    
    case ASTNodeType.IDENTIFIER:
      return node.name;
    
    case ASTNodeType.VECTOR_LITERAL: {
      const elements = (node.elements || []).map((e: any) => compileExpression(e));
      const type = node.vectorType || 'vec4<f32>';
      return `${type}(${elements.join(', ')})`;
    }
    
    case ASTNodeType.BINARY_EXPR: {
      const left = compileExpression(node.left);
      const right = compileExpression(node.right);
      const op = mapBinaryOp(node.operator);
      return `(${left} ${op} ${right})`;
    }
    
    case ASTNodeType.UNARY_EXPR: {
      const operand = compileExpression(node.operand);
      return `(${node.operator}${operand})`;
    }
    
    case ASTNodeType.FUNCTION_CALL: {
      const args = (node.args || []).map((a: any) => compileExpression(a));
      return `${node.name}(${args.join(', ')})`;
    }
    
    case ASTNodeType.MEMBER_ACCESS: {
      const obj = compileExpression(node.object);
      return `${obj}.${node.member}`;
    }
    
    default:
      return `/* unknown expr: ${node.type} */`;
  }
}

/**
 * Map GSPL binary operators to WGSL
 */
function mapBinaryOp(op: string): string {
  const mapping: Record<string, string> = {
    '+': '+',
    '-': '-',
    '*': '*',
    '/': '/',
    '%': '%',
    '==': '==',
    '!=': '!=',
    '<': '<',
    '>': '>',
    '<=': '<=',
    '>=': '>=',
    '&&': '&&',
    '||': '||',
    // GSPL-specific
    '..': '..', // Range operator (not in WGSL, would need loop)
  };
  return mapping[op] || op;
}

/**
 * Map GSPL types to WGSL types
 */
function mapGSLTypeToWGSL(gsplType: string): string {
  const mapping: Record<string, string> = {
    'scalar': 'f32',
    'int': 'i32',
    'float': 'f32',
    'bool': 'bool',
    'vec2': 'vec2<f32>',
    'vec3': 'vec3<f32>',
    'vec4': 'vec4<f32>',
    'mat2': 'mat2x2<f32>',
    'mat3': 'mat3x3<f32>',
    'mat4': 'mat4x4<f32>',
    'void': 'void',
  };
  return mapping[gsplType] || 'f32';
}

/**
 * Generate WGSL utility functions
 */
function generateUtilities(): string {
  return `
// Common math utilities
fn mix(a: f32, b: f32, t: f32) -> f32 {
  return a * (1.0 - t) + b * t;
}

fn clamp(x: f32, minVal: f32, maxVal: f32) -> f32 {
  return min(max(x, minVal), maxVal);
}

fn smoothstep(edge0: f32, edge1: f32, x: f32) -> f32 {
  let t = clamp((x - edge0) / (edge1 - edge0), 0.0, 1.0);
  return t * t * (3.0 - 2.0 * t);
}

// Vector utilities
fn length2(v: vec2<f32>) -> f32 {
  return sqrt(v.x * v.x + v.y * v.y);
}

fn length3(v: vec3<f32>) -> f32 {
  return sqrt(v.x * v.x + v.y * v.y + v.z * v.z);
}

// Noise functions (simplified)
fn random2D(p: vec2<f32>) -> f32 {
  return fract(sin(dot(p, vec2<f32>(12.9898, 78.233))) * 43758.5453;
}

`;
}

/**
 * Example: Compile a Mandelbrot function
 */
export function compileMandelbrotExample(): string {
  const exampleGSPL = `
@gpu
fn mandelbrot(c: vec2<f32>) -> f32 {
  let z = vec2<f32>(0.0, 0.0);
  for (i in 0..256) {
    z = vec2<f32>(z.x * z.x - z.y * z.y + c.x, 2.0 * z.x * z.y + c.y);
    if (length(z) > 2.0) {
      return i as f32;
    }
  }
  return 256.0;
}
`;
  
  // Parse would happen here (simplified)
  const wgsl = `
fn mandelbrot(c: vec2<f32>) -> f32 {
  var z: vec2<f32> = vec2<f32>(0.0, 0.0);
  for (var i: i32 = 0; i < 256; i++) {
    z = vec2<f32>(z.x * z.x - z.y * z.y + c.x, 2.0 * z.x * z.y + c.y);
    if (length(z) > 2.0) {
      return f32(i);
    }
  }
  return 256.0;
}
`;
  
  return wgsl;
}

/**
 * Integrate with GSPL Interpreter
 * Call this when @gpu directive is encountered
 */
export function handleGPUDirective(
  funcName: string,
  ast: ASTNode[]
): WebGPUComputePipeline | null {
  const result = compileToWGSL(ast);
  
  if (result.errors.length > 0) {
    console.error('WGSL compilation errors:', result.errors);
    return null;
  }
  
  // In production: create GPU compute pipeline
  console.log('WGSL Code:\n', result.wgslCode);
  
  return null; // Placeholder
}
