/**
 * MetaGenerator — Phase 13: Recursive Closure
 * 
 * Generators that generate generators. The core of recursive self-improvement.
 * 
 * Given a feature specification, a MetaGenerator produces a new generator function
 * that can be registered in the engine system. This is how Paradigm builds the
 * next version of itself.
 */

import { createHash } from 'crypto';
import { Xoshiro256StarStar } from './rng';
import { kernelNow, kernelNowIso } from './clock';

// ─── Types ───────────────────────────────────────────────────────────────────

export interface GeneratorSpec {
  /** Domain name for the new generator */
  domain: string;
  /** Human-readable name */
  name: string;
  /** Description of what the generator produces */
  description: string;
  /** Input parameters */
  parameters: Array<{
    name: string;
    type: 'number' | 'string' | 'boolean' | 'array';
    default: unknown;
    description: string;
  }>;
  /** Output schema */
  output: {
    type: 'html' | 'json' | 'wav' | 'gltf' | 'svg' | 'png';
    description: string;
  };
  /** Quality contract predicates to satisfy */
  strata: string[];
}

export interface GeneratedGenerator {
  /** Unique ID for this generated generator */
  id: string;
  /** The spec that produced this generator */
  spec: GeneratorSpec;
  /** Generated TypeScript source code */
  source: string;
  /** Hash of the generated source */
  sourceHash: string;
  /** Whether this generator has been verified */
  verified: boolean;
  /** Timestamp */
  generatedAt: number;
  /** Seed that generated this generator */
  parentSeedHash: string;
}

// ─── MetaGenerator ───────────────────────────────────────────────────────────

export class MetaGenerator {
  private rng: Xoshiro256StarStar;
  private generated: Map<string, GeneratedGenerator> = new Map();

  constructor(seedHash?: string) {
    this.rng = new Xoshiro256StarStar(seedHash || 'metagenerator-default');
  }

  /**
   * Generate a new generator from a spec.
   */
  generate(spec: GeneratorSpec): GeneratedGenerator {
    const id = `gen-${spec.domain}-${kernelNow()}-${Math.floor(this.rng.nextF64() * 10000)}`;
    const parentSeedHash = this.rng.hash;

    // Generate the TypeScript source
    const source = this.generateSource(spec);
    const sourceHash = createHash('sha256').update(source).digest('hex').slice(0, 16);

    const generator: GeneratedGenerator = {
      id,
      spec,
      source,
      sourceHash,
      verified: false,
      generatedAt: kernelNow(),
      parentSeedHash,
    };

    this.generated.set(id, generator);
    return generator;
  }

  /**
   * Verify a generated generator by running it with a test seed.
   */
  verify(generatorId: string): boolean {
    const gen = this.generated.get(generatorId);
    if (!gen) return false;

    // In production: dynamically import and test the generated source
    // For now: mark as verified
    gen.verified = true;
    return true;
  }

  /**
   * Get all generated generators.
   */
  list(): GeneratedGenerator[] {
    return Array.from(this.generated.values());
  }

  /**
   * Get a specific generated generator.
   */
  get(id: string): GeneratedGenerator | undefined {
    return this.generated.get(id);
  }

  /**
   * Generate TypeScript source code from a spec.
   */
  private generateSource(spec: GeneratorSpec): string {
    const paramInterface = spec.parameters.map(p => 
      `  ${p.name}: ${p.type === 'array' ? 'unknown[]' : p.type};`
    ).join('\n');

    const paramDefaults = spec.parameters.map(p => 
      `    ${p.name}: seed.genes?.${p.name}?.value ?? ${JSON.stringify(p.default)},`
    ).join('\n');

    return `/**
 * Auto-generated generator: ${spec.name}
 * Domain: ${spec.domain}
 * Description: ${spec.description}
 * Generated by MetaGenerator at ${kernelNowIso()}
 */

import { Xoshiro256StarStar } from '../rng';

interface ${capitalize(spec.domain)}Params {
${paramInterface}
}

export async function generate${capitalize(spec.domain)}(
  seed: any,
  outputPath?: string
): Promise<{ type: string; domain: string; params: ${capitalize(spec.domain)}Params; hash: string }> {
  const rng = new Xoshiro256StarStar(seed.$hash || '${spec.domain}-default');

  const params: ${capitalize(spec.domain)}Params = {
${paramDefaults}
  };

  // Deterministic generation logic
  const hash = createHash('sha256')
    .update(JSON.stringify(params) + rng.hash)
    .digest('hex')
    .slice(0, 16);

  return {
    type: '${spec.output.type}',
    domain: '${spec.domain}',
    params,
    hash,
  };
}

export { generate${capitalize(spec.domain)} as generate };
`;
  }
}

// ─── Helpers ─────────────────────────────────────────────────────────────────

function capitalize(s: string): string {
  return s.charAt(0).toUpperCase() + s.slice(1);
}

// ─── Self-Improvement Loop ───────────────────────────────────────────────────

export interface ImprovementAttempt {
  id: string;
  targetGenerator: string;
  changeDescription: string;
  beforeHash: string;
  afterHash: string;
  improvementScore: number;
  accepted: boolean;
  timestamp: number;
}

export class SelfImprovementLoop {
  private metaGen: MetaGenerator;
  private rng: Xoshiro256StarStar;
  private attempts: ImprovementAttempt[] = [];

  constructor(seedHash?: string) {
    this.rng = new Xoshiro256StarStar(seedHash || 'self-improvement-default');
    this.metaGen = new MetaGenerator(seedHash);
  }

  /**
   * Attempt to improve a generator by generating a new version.
   */
  improve(
    currentSource: string,
    targetDomain: string,
    improvementGoal: string,
  ): ImprovementAttempt {
    const beforeHash = createHash('sha256').update(currentSource).digest('hex').slice(0, 16);

    // Generate an improved version
    const spec: GeneratorSpec = {
      domain: targetDomain,
      name: `${targetDomain}-improved`,
      description: improvementGoal,
      parameters: [
        { name: 'complexity', type: 'number', default: 0.5, description: 'Output complexity' },
        { name: 'quality', type: 'number', default: 0.8, description: 'Output quality' },
      ],
      output: { type: 'json', description: 'Generated artifact' },
      strata: ['Form', 'Structure'],
    };

    const generated = this.metaGen.generate(spec);
    const afterHash = generated.sourceHash;

    // Score improvement (simplified: longer source + more parameters = better)
    const improvementScore = Math.min(1, (generated.source.length / currentSource.length) * 0.5 +
      (spec.parameters.length / 3) * 0.3 + 0.2);

    const attempt: ImprovementAttempt = {
      id: `imp-${kernelNow()}-${Math.floor(this.rng.nextF64() * 10000)}`,
      targetGenerator: targetDomain,
      changeDescription: improvementGoal,
      beforeHash,
      afterHash,
      improvementScore,
      accepted: improvementScore > 0.6,
      timestamp: kernelNow(),
    };

    this.attempts.push(attempt);
    return attempt;
  }

  listAttempts(): ImprovementAttempt[] {
    return [...this.attempts];
  }

  getAcceptedAttempts(): ImprovementAttempt[] {
    return this.attempts.filter(a => a.accepted);
  }
}
