/**
 * Template Bridge — words → gene-path distributions
 *
 * Source: PAradigm-reference/intelligence/template-bridge.md
 *
 * A "template" is a named recipe that declares which gene paths a
 * particular kind of seed needs, plus default values and sub-agent
 * weights. The Sovereign Agent uses templates to:
 *   - know which gene paths Stage 4 (assemble) should write to
 *   - know which sub-agents to consult in Stage 2 (resolve)
 *   - seed defaults when no sub-agent contributes a value
 *
 * Templates are immutable, deterministic, and ship as data — never
 * generated by the LLM. Adding a new domain = adding a new template.
 */

import type { TopLevelIntent } from './types';

export interface TemplatePath {
  path: string;
  /** Default value if no sub-agent contributes one. */
  default: number | string | number[] | string[];
  /** Which sub-agents are authoritative for this path. */
  authoritative: SubAgentName[];
  /** Optional gene-value range hint for validators. */
  range?: [number, number];
  /** Optional list of allowed string values. */
  enum?: string[];
}

export type SubAgentName =
  | 'VisionAgent'
  | 'PersonalityAgent'
  | 'MusicTheoryAgent'
  | 'NarrativeAgent'
  | 'MechanicsAgent'
  | 'PhysicsAgent'
  | 'StyleAgent'
  | 'CritiqueAgent';

export interface Template {
  id: string;
  domain: string;
  /** Top-level intents this template responds to. */
  intents: TopLevelIntent[];
  /** Sub-intents this template responds to. */
  subIntents: string[];
  /** Sub-agents to run (and their relative weight). */
  subAgents: Partial<Record<SubAgentName, number>>;
  /** Gene paths this template populates. */
  paths: TemplatePath[];
  /** Human-readable summary for prompts. */
  summary: string;
}

// ─── Built-in templates ───────────────────────────────────────────────────

export const TEMPLATES: readonly Template[] = [
  {
    id: 'character',
    domain: 'character',
    intents: ['CREATE', 'EVOLVE', 'BREED'],
    subIntents: ['character', 'hero', 'antagonist', 'npc', 'protagonist'],
    subAgents: {
      VisionAgent: 0.8,
      PersonalityAgent: 1.0,
      StyleAgent: 0.7,
      CritiqueAgent: 1.0,
    },
    paths: [
      { path: 'visual.hue', default: 0.5, authoritative: ['VisionAgent'], range: [0, 360] },
      { path: 'visual.saturation', default: 0.6, authoritative: ['VisionAgent'], range: [0, 1] },
      { path: 'visual.lightness', default: 0.5, authoritative: ['VisionAgent'], range: [0, 1] },
      { path: 'visual.palette', default: ['#888'], authoritative: ['VisionAgent'] },
      { path: 'body.bigFive.openness', default: 0.5, authoritative: ['PersonalityAgent'] },
      { path: 'body.bigFive.conscientiousness', default: 0.5, authoritative: ['PersonalityAgent'] },
      { path: 'body.bigFive.extraversion', default: 0.5, authoritative: ['PersonalityAgent'] },
      { path: 'body.bigFive.agreeableness', default: 0.5, authoritative: ['PersonalityAgent'] },
      { path: 'body.bigFive.neuroticism', default: 0.5, authoritative: ['PersonalityAgent'] },
      { path: 'body.attachment', default: 'secure', authoritative: ['PersonalityAgent'],
        enum: ['secure', 'anxious', 'avoidant', 'disorganized'] },
      { path: 'persona.archetype', default: 'everyman', authoritative: ['PersonalityAgent'] },
      { path: 'style.movement', default: 'realist', authoritative: ['StyleAgent'] },
      { path: 'style.era', default: 'modern', authoritative: ['StyleAgent'] },
      { path: 'style.medium', default: 'digital', authoritative: ['StyleAgent'] },
    ],
    summary: 'A character seed: visual identity + Big-Five personality + archetype + style envelope.',
  },
  {
    id: 'friend',
    domain: 'friend',
    intents: ['CREATE', 'EVOLVE', 'BREED'],
    subIntents: ['friend', 'companion', 'ally', 'sidekick'],
    subAgents: {
      VisionAgent: 0.7,
      PersonalityAgent: 1.0,
      StyleAgent: 0.5,
      NarrativeAgent: 0.6,
      CritiqueAgent: 1.0,
    },
    paths: [
      { path: 'body.bigFive.openness', default: 0.6, authoritative: ['PersonalityAgent'] },
      { path: 'body.bigFive.conscientiousness', default: 0.6, authoritative: ['PersonalityAgent'] },
      { path: 'body.bigFive.extraversion', default: 0.6, authoritative: ['PersonalityAgent'] },
      { path: 'body.bigFive.agreeableness', default: 0.7, authoritative: ['PersonalityAgent'] },
      { path: 'body.bigFive.neuroticism', default: 0.4, authoritative: ['PersonalityAgent'] },
      { path: 'body.attachment', default: 'secure', authoritative: ['PersonalityAgent'] },
      { path: 'bond.warmth', default: 0.7, authoritative: ['PersonalityAgent'] },
      { path: 'bond.trust', default: 0.6, authoritative: ['PersonalityAgent'] },
      { path: 'bond.loyalty', default: 0.7, authoritative: ['PersonalityAgent'] },
      { path: 'persona.archetype', default: 'caregiver', authoritative: ['PersonalityAgent'] },
      { path: 'narrative.tone', default: 'heroic', authoritative: ['NarrativeAgent'] },
    ],
    summary: 'A friend seed: a sympathetic companion biased toward warmth, loyalty, and prosocial archetypes.',
  },
  {
    id: 'music',
    domain: 'music',
    intents: ['CREATE', 'EVOLVE', 'COMPOSE'],
    subIntents: ['music', 'song', 'theme', 'soundtrack', 'cue'],
    subAgents: {
      MusicTheoryAgent: 1.0,
      StyleAgent: 0.8,
      CritiqueAgent: 1.0,
    },
    paths: [
      { path: 'music.key', default: 'C', authoritative: ['MusicTheoryAgent'] },
      { path: 'music.mode', default: 'major', authoritative: ['MusicTheoryAgent'] },
      { path: 'music.tempo', default: 100, authoritative: ['MusicTheoryAgent'], range: [40, 220] },
      { path: 'music.timeSig', default: '4/4', authoritative: ['MusicTheoryAgent'] },
      { path: 'music.instrument', default: 'piano', authoritative: ['MusicTheoryAgent'] },
      { path: 'music.dynamics', default: 'mf', authoritative: ['MusicTheoryAgent'] },
      { path: 'music.harmonic.density', default: 0.5, authoritative: ['MusicTheoryAgent'] },
      { path: 'style.movement', default: 'romantic', authoritative: ['StyleAgent'] },
      { path: 'style.era', default: 'modern', authoritative: ['StyleAgent'] },
    ],
    summary: 'A music seed: key + mode + tempo + instrumentation + style envelope.',
  },
  {
    id: 'world',
    domain: 'world',
    intents: ['CREATE', 'EVOLVE', 'COMPOSE'],
    subIntents: ['world', 'setting', 'biome', 'environment', 'location'],
    subAgents: {
      VisionAgent: 0.8,
      PhysicsAgent: 0.9,
      StyleAgent: 0.7,
      NarrativeAgent: 0.6,
      CritiqueAgent: 1.0,
    },
    paths: [
      { path: 'physics.gravity', default: 9.8, authoritative: ['PhysicsAgent'], range: [0, 30] },
      { path: 'physics.friction', default: 0.4, authoritative: ['PhysicsAgent'] },
      { path: 'physics.lightDecay', default: 0.3, authoritative: ['PhysicsAgent'] },
      { path: 'physics.atmosphere', default: 'normal', authoritative: ['PhysicsAgent'] },
      { path: 'visual.hue', default: 0.5, authoritative: ['VisionAgent'] },
      { path: 'visual.palette', default: ['#88a', '#aa8'], authoritative: ['VisionAgent'] },
      { path: 'style.movement', default: 'realist', authoritative: ['StyleAgent'] },
      { path: 'style.era', default: 'modern', authoritative: ['StyleAgent'] },
    ],
    summary: 'A world seed: physical laws + visual palette + style envelope.',
  },
  {
    id: 'game',
    domain: 'game',
    intents: ['CREATE', 'EVOLVE', 'COMPOSE'],
    subIntents: ['game', 'quest', 'level', 'challenge'],
    subAgents: {
      MechanicsAgent: 1.0,
      NarrativeAgent: 0.8,
      PhysicsAgent: 0.6,
      VisionAgent: 0.5,
      CritiqueAgent: 1.0,
    },
    paths: [
      { path: 'mechanics.coreLoop', default: 'exploration', authoritative: ['MechanicsAgent'] },
      { path: 'mechanics.difficulty', default: 0.5, authoritative: ['MechanicsAgent'] },
      { path: 'mechanics.difficultyCurve', default: 'sigmoid', authoritative: ['MechanicsAgent'] },
      { path: 'mechanics.agency', default: 0.7, authoritative: ['MechanicsAgent'] },
      { path: 'mechanics.permadeath', default: 0, authoritative: ['MechanicsAgent'] },
      { path: 'narrative.structure', default: 'hero\'s-journey', authoritative: ['NarrativeAgent'] },
      { path: 'narrative.pacing', default: 0.5, authoritative: ['NarrativeAgent'] },
    ],
    summary: 'A game seed: core loop + difficulty curve + narrative structure + agency.',
  },
  {
    id: 'narrative',
    domain: 'narrative',
    intents: ['CREATE', 'EVOLVE', 'COMPOSE'],
    subIntents: ['narrative', 'story', 'plot', 'scene', 'dialogue'],
    subAgents: {
      NarrativeAgent: 1.0,
      PersonalityAgent: 0.6,
      StyleAgent: 0.6,
      CritiqueAgent: 1.0,
    },
    paths: [
      { path: 'narrative.structure', default: 'three-act', authoritative: ['NarrativeAgent'] },
      { path: 'narrative.tone', default: 'heroic', authoritative: ['NarrativeAgent'] },
      { path: 'narrative.pacing', default: 0.5, authoritative: ['NarrativeAgent'] },
      { path: 'narrative.pov', default: 'third', authoritative: ['NarrativeAgent'] },
      { path: 'narrative.themes', default: ['discovery'], authoritative: ['NarrativeAgent'] },
      { path: 'style.movement', default: 'realist', authoritative: ['StyleAgent'] },
    ],
    summary: 'A narrative seed: structure + tone + pacing + POV + themes.',
  },
];

const TEMPLATES_BY_ID: Map<string, Template> = new Map(TEMPLATES.map((t) => [t.id, t]));
const TEMPLATES_BY_DOMAIN: Map<string, Template> = new Map(TEMPLATES.map((t) => [t.domain, t]));

export function templateById(id: string): Template | undefined {
  return TEMPLATES_BY_ID.get(id);
}
export function templateForDomain(domain: string): Template | undefined {
  return TEMPLATES_BY_DOMAIN.get(domain);
}

/**
 * Pick the best template for a parsed intent.
 *
 * Scoring:
 *   +2 if the top-level intent matches
 *   +3 if any sub-intent matches the parsed sub-intent
 *   +1 for each domain string the parsed intent named that the template handles
 */
export function selectTemplate(
  top: TopLevelIntent,
  subIntent: string,
  domains: string[],
): Template {
  let best = TEMPLATES[0];
  let bestScore = -Infinity;
  for (const t of TEMPLATES) {
    let s = 0;
    if (t.intents.includes(top)) s += 2;
    if (t.subIntents.includes(subIntent)) s += 3;
    for (const d of domains) if (t.domain === d) s += 1;
    if (s > bestScore) {
      bestScore = s;
      best = t;
    }
  }
  return best;
}

/** All gene paths the template expects to populate. */
export function pathsFor(template: Template): string[] {
  return template.paths.map((p) => p.path);
}

/** Default-value lookup for a single gene path. */
export function defaultFor(template: Template, path: string): TemplatePath['default'] | undefined {
  return template.paths.find((p) => p.path === path)?.default;
}
