#!/usr/bin/env bun
/**
 * generate-contracts-loader.ts
 *
 * Emit `src/lib/kernel/generators/contracts.ts` — a side-effect barrel
 * that imports every `*-contract.ts` in this directory so the contracts
 * register themselves at app boot. Without this barrel, the contract
 * files are dormant code and `listContracts()` returns empty.
 *
 * Run before commit; CI will fail if the file is out of date.
 */
import { readdirSync, writeFileSync, readFileSync } from 'node:fs';
import { join } from 'node:path';
import crypto from 'node:crypto';

const GEN_DIR = 'src/lib/kernel/generators';
const OUT = join(GEN_DIR, 'contracts.ts');
const APPLY = process.argv.includes('--apply') || !process.argv.includes('--check');

const files = readdirSync(GEN_DIR)
  .filter((f) => f.endsWith('-contract.ts'))
  .sort();

const lines = [
  '/**',
  ' * Generator contracts barrel — auto-generated by scripts/generate-contracts-loader.ts.',
  ` * ${files.length} contracts registered on import. Do not edit by hand.`,
  ' */',
  '',
  ...files.map((f) => `import './${f.replace(/\.ts$/, '')}';`),
  '',
  'export const CONTRACTS_REGISTERED = ' + files.length + ';',
  '',
];
const generated = lines.join('\n');

if (process.argv.includes('--check')) {
  let current = '';
  try { current = readFileSync(OUT, 'utf8'); } catch { /* missing is "drift" */ }
  if (current !== generated) {
    console.error('❌ contracts.ts is out of date. Re-run: bun run scripts/generate-contracts-loader.ts --apply');
    process.exit(1);
  }
  console.log('✅ contracts.ts is up to date');
  process.exit(0);
}

if (APPLY) {
  writeFileSync(OUT, generated);
  const sha = crypto.createHash('sha1').update(generated).digest('hex').slice(0, 8);
  console.log(`wrote ${OUT} (${files.length} contracts, sha=${sha})`);
}
