#!/usr/bin/env -S npx tsx
/**
 * Paradigm Quality Contract — CLI report.
 * Loads every contract that self-registers, runs conformance against
 * each, prints the leaderboard, exits non-zero if any contract fails.
 */
import '../src/lib/friend/contract';
import '../src/lib/world/contract';
import '../src/lib/game/contract';
import '../src/lib/kernel/generators/sprite-contract';
import '../src/lib/kernel/generators/music-contract';
import '../src/lib/kernel/generators/narrative-contract';
import '../src/lib/kernel/generators/visual2d-contract';
import '../src/lib/kernel/generators/geometry3d-contract';
import '../src/lib/kernel/generators/character-contract';
import '../src/lib/kernel/generators/audio-contract';
import '../src/lib/kernel/generators/dance-contract';
import '../src/lib/kernel/generators/physics-contract';
import '../src/lib/kernel/generators/typography-contract';
import '../src/lib/kernel/generators/particle-contract';
import '../src/lib/kernel/generators/shader-contract';
import '../src/lib/kernel/generators/optics-contract';
import '../src/lib/kernel/generators/animation-contract';
import '../src/lib/kernel/generators/ecosystem-contract';
import '../src/lib/kernel/generators/edtech-contract';
import '../src/lib/kernel/generators/education-contract';
import '../src/lib/kernel/generators/fashion-contract';
import '../src/lib/kernel/generators/architecture-contract';
import '../src/lib/kernel/generators/cybersecurity-contract';
import '../src/lib/kernel/generators/finance-contract';
import '../src/lib/kernel/generators/healthcare-contract';
import { runAllConformance, formatLeaderboard } from '../src/lib/kernel/quality-contract';

const results = await runAllConformance();
console.log('\n' + formatLeaderboard(results) + '\n');
const failing = results.filter((r) => !r.passed);
if (failing.length > 0) {
  console.error(`✗ ${failing.length} contract(s) failed:`);
  for (const r of failing) console.error(`  - ${r.domain}@${r.version}`);
  process.exit(1);
}
console.log(`✓ ${results.length} contract(s) green.\n`);
import '../src/lib/kernel/generators/advertising-contract';
import '../src/lib/kernel/generators/automotive-contract';
import '../src/lib/kernel/generators/blockchain-contract';
import '../src/lib/kernel/generators/art-contract';
import '../src/lib/kernel/generators/legal-contract';
import '../src/lib/kernel/generators/agriculture-contract';
import '../src/lib/kernel/generators/aerospace-contract';
import '../src/lib/kernel/generators/beer-contract';
import '../src/lib/kernel/generators/biotechnology-contract';
import '../src/lib/kernel/generators/chemical-contract';
import '../src/lib/kernel/generators/marine-contract';
import '../src/lib/kernel/generators/retail-contract';
import '../src/lib/kernel/generators/sports-contract';
import '../src/lib/kernel/generators/transportation-contract';
import '../src/lib/kernel/generators/wine-contract';
import '../src/lib/kernel/generators/manufacturing-contract';
import '../src/lib/kernel/generators/acoustics-contract';
import '../src/lib/kernel/generators/circuit-contract';
import '../src/lib/kernel/generators/city-contract';
import '../src/lib/kernel/generators/climate-contract';
import '../src/lib/kernel/generators/cloud-contract';
import '../src/lib/kernel/generators/devops-contract';
import '../src/lib/kernel/generators/energy-contract';
import '../src/lib/kernel/generators/entertainment-contract';
import '../src/lib/kernel/generators/film-contract';
import '../src/lib/kernel/generators/fitness-contract';
import '../src/lib/kernel/generators/food-contract';
import '../src/lib/kernel/generators/robotics-contract';
import '../src/lib/kernel/generators/coffee-contract';
import '../src/lib/kernel/generators/cosmetics-contract';
import '../src/lib/kernel/generators/electronics-contract';
import '../src/lib/kernel/generators/gardening-contract';
import '../src/lib/kernel/generators/gaming-contract';
import '../src/lib/kernel/generators/theater-contract';
import '../src/lib/kernel/generators/photography-contract';
import '../src/lib/kernel/generators/construction-contract';
import '../src/lib/kernel/generators/furniture-contract';
import '../src/lib/kernel/generators/genomics-contract';
import '../src/lib/kernel/generators/hospitality-contract';
import '../src/lib/kernel/generators/insurance-contract';
import '../src/lib/kernel/generators/journalism-contract';
import '../src/lib/kernel/generators/landscaping-contract';
import '../src/lib/kernel/generators/lighting-contract';
import '../src/lib/kernel/generators/literature-contract';
import '../src/lib/kernel/generators/logistics-contract';
import '../src/lib/kernel/generators/marketing-contract';
import '../src/lib/kernel/generators/material-contract';
import '../src/lib/kernel/generators/media-contract';
import '../src/lib/kernel/generators/metaverse-contract';
import '../src/lib/kernel/generators/nanotechnology-contract';
import '../src/lib/kernel/generators/neuroscience-contract';
import '../src/lib/kernel/generators/procedural-contract';
import '../src/lib/kernel/generators/protein-contract';
import '../src/lib/kernel/generators/publishing-contract';
import '../src/lib/kernel/generators/reactor-contract';
import '../src/lib/kernel/generators/semiconductors-contract';
import '../src/lib/kernel/generators/sensors-contract';
import '../src/lib/kernel/generators/textiles-contract';
import '../src/lib/kernel/generators/tourism-contract';
import '../src/lib/kernel/generators/universe-contract';
import '../src/lib/kernel/generators/security-contract';
import '../src/lib/kernel/generators/alife-contract';
import '../src/lib/kernel/generators/biomedical-contract';
import '../src/lib/kernel/generators/drones-contract';
import '../src/lib/kernel/generators/drug-contract';
import '../src/lib/kernel/generators/jewelry-contract';
import '../src/lib/kernel/generators/market-contract';
import '../src/lib/kernel/generators/nanobot-contract';
import '../src/lib/kernel/generators/spirits-contract';
import '../src/lib/kernel/generators/tea-contract';
import '../src/lib/kernel/generators/telecommunications-contract';
import '../src/lib/kernel/generators/ui-contract';
import '../src/lib/kernel/generators/vehicle-contract';
import '../src/lib/kernel/generators/vr-contract';
import '../src/lib/kernel/generators/wearables-contract';
import '../src/lib/kernel/generators/ar-contract';
import '../src/lib/kernel/generators/av-contract';
import '../src/lib/kernel/generators/battery-contract';
import '../src/lib/kernel/generators/event-planning-contract';
import '../src/lib/kernel/generators/real-estate-contract';
import '../src/lib/kernel/generators/smart-home-contract';
import '../src/lib/kernel/generators/choreography-contract';
import '../src/lib/kernel/generators/drone-delivery-contract';
import '../src/lib/kernel/generators/food-delivery-contract';
import '../src/lib/kernel/generators/food-service-contract';
import '../src/lib/kernel/generators/interior-design-contract';
import '../src/lib/kernel/generators/pet-care-contract';
import '../src/lib/kernel/generators/renewable-energy-contract';
import '../src/lib/kernel/generators/smart-grid-contract';
import '../src/lib/kernel/generators/space-tourism-contract';
import '../src/lib/kernel/generators/synthetic-biology-contract';
import '../src/lib/kernel/generators/personalized-medicine-contract';
import '../src/lib/kernel/generators/agtech-contract';
import '../src/lib/kernel/generators/consciousness-contract';
import '../src/lib/kernel/generators/quantum-circuit-contract';
import '../src/lib/kernel/generators/quantum-computing-contract';
import '../src/lib/kernel/generators/robotics-industrial-contract';
import '../src/lib/kernel/generators/visual2d-svg-contract';
import '../src/lib/kernel/generators/genome-contract';
import '../src/lib/kernel/generators/ml-contract';
