/**
 * Sovereignty + GSPL export routes (slice of the modular router split).
 *
 * Extracted from server.ts lines ~487-559 by paradigm-infinite/ws-17.
 * Doctrine: 12_PARADIGM_INFINITE_COMPLETION_DOCTRINE.md — server.ts
 * decomposition workstream.
 */
import type { Express, Request, Response, RequestHandler } from 'express';

interface SovereigntyDeps {
  optionalAuth: RequestHandler;
  seeds: any[];
}

function hashSlice(seed: any): string {
  return (seed?.$hash ?? 'x').slice(0, 8);
}

export function registerSovereigntyRoutes(app: Express, deps: SovereigntyDeps): void {
  const { optionalAuth, seeds } = deps;

  app.get('/api/sovereignty/receipt', optionalAuth, async (req: any, res: any) => {
    const hash = req.query.hash as string;
    if (!hash) return res.status(400).json({ error: 'hash required' });
    const seed = seeds.find((s: any) => s.$hash === hash || s.id === hash);
    if (!seed) return res.status(404).json({ error: 'Seed not found' });

    const receipt = {
      seedHash: hash,
      domain: seed.$domain ?? 'unknown',
      sovereignty: {
        signed: !!seed.$sovereignty?.signature,
        valid: seed.$sovereignty?.signature ? true : null,
        publicKeyFingerprint: seed.$sovereignty?.author_pubkey ?? null,
        algorithm: 'ECDSA P-256',
        signedAt: seed.$sovereignty?.timestamp ?? null,
      },
      lineage: (seed.$lineage ?? []).slice(0, 8).map((h: string, i: number) => ({
        hash: h,
        depth: i + 1,
        domain: seed.$domain ?? 'unknown',
        operation: 'mutate',
      })),
      commits: [],
      anchor: { minted: false },
    };
    res.json(receipt);
  });

  app.post('/api/sovereignty/export/gseed', optionalAuth, async (req: any, res: any) => {
    const { seed } = req.body;
    if (!seed) return res.status(400).json({ error: 'seed required' });
    try {
      const { encodeGseed, CURRENT_VERSION, canCompressSections } = await import(
        '../../lib/kernel/binary-format.js'
      );
      const pkg = {
        version: CURRENT_VERSION,
        timestamp: Date.now(),
        flags: {
          hasC2PA: false,
          hasOutputs: false,
          encryptedSeed: false,
          royaltyEnabled: false,
          compressed: canCompressSections(),
        },
        seedHash:
          seed.$hash ??
          '000000000000000000000000000000000000000000000000000000000000000',
        metadata: {
          schema: 'https://paradigm.ai/schema/gseed-metadata/v1',
          author: 'Anonymous',
          title: `Exported ${seed.$domain ?? 'unknown'}`,
          generator: seed.$domain ?? 'unknown',
          license: 'CC0',
        },
        params: seed,
        outputs: [],
      };
      const buf = encodeGseed(pkg);
      res.setHeader(
        'Content-Disposition',
        `attachment; filename="seed-${hashSlice(seed)}.gseed"`,
      );
      res.type('application/octet-stream').send(Buffer.from(buf));
    } catch (e: any) {
      res.status(500).json({ error: e.message });
    }
  });

  app.post('/api/gspl/export', optionalAuth, async (req: any, res: any) => {
    const { seed, domain } = req.body;
    if (!seed) return res.status(400).json({ error: 'seed required' });
    const genes = (seed as any).genes ?? seed;
    const geneLines = Object.entries(genes)
      .filter(([k]) => !k.startsWith('$'))
      .map(([k, v]: [string, any]) => {
        const type = v?.gene_type ?? v?.type ?? 'scalar';
        const value = JSON.stringify(v?.value ?? v);
        return `  gene ${k}: ${type} = ${value}`;
      })
      .join('\n');
    const gspl = `// Generated by Paradigm\nimport "std/core";\n\nseed ${(domain ?? seed.$domain ?? 'Unnamed').replace(/[^a-zA-Z0-9]/g, '_')} {\n${geneLines}\n}\n`;
    res.setHeader(
      'Content-Disposition',
      `attachment; filename="seed-${hashSlice(seed)}.gspl"`,
    );
    res.type('text/plain').send(gspl);
  });
}
